import { LayoutDataProvider } from '@/app/providers/UseLayoutData';
import React, { cache } from 'react'



const getCategory = cache(async (id) => {
    return await {
        title: "Category-" + id,
        description: "Generated by create next app",
    };
});




export async function generateMetadata({ params }) {
    const { id } = await params;
    const category = await getCategory(id)

    return {
        title: category?.title || "Default Title",
        description: category?.description || "Default Description",
        // openGraph: {
        //     title: post?.title || "Default Title",
        //     description: post?.excerpt || "Default description",
        //     images: post?.image ? [{ url: post.image, width: 1200, height: 630 }] : [],
        // },
    };
}
async function layout({
    params,
    children
}) {
    const { id } = await params;
    const category = {
        id: id,
        title: "Category " + id,
        
    }
    return (
        <LayoutDataProvider value={category}>
            {children}
        </LayoutDataProvider>
    )
}

export default layout