import AccordionSegment from '@/components/ui/accordionSegment';
import { Button } from '@/components/ui/button';
import { Icon } from '@iconify/react';
import Link from 'next/link';
import React from 'react'


export const generateMetadata = async () => {
    return {
        title: "Help Center",
        // description: "Generated by create next app",
    };
};
function page() {


    return (
        <section className="py-10 lg:py-20">
            <div className="container">
                <h3
                    className='text-3xl font-bold lg:text-5xl'>
                    Help Center
                </h3>
                <p className="mt-5 txt">
                    Welcome to the Help and Support page of HelpRush, where we are dedicated to assisting you with any questions, concerns, or issues you may encounter while using our platform. Your satisfaction and seamless experience are our top priorities.
                </p>
                <h4 className="mt-10 text-xl lg:mt-20 font-bold lg:text-3xl">
                    Frequently Asked Questions (FAQs)
                </h4>
                <p className="mt-5 txt">
                    Before reaching out to our support team, please consider checking our Frequently Asked Questions (FAQs) section. Here, you may find answers to common queries related to using HelpRush, including:

                </p>

                <div className='grid grid-cols-2 lg:grid-cols-3 gap-4 mt-5'>
                    <a href="#" className='text-theme  font-medium'>
                        <Icon icon="stash:user-cog" className='text-5xl mb-2 c_icon' />
                        Account setup and management.
                    </a>
                    <a href="#" className='text-theme  font-medium'>
                        <Icon icon="akar-icons:schedule" className='text-5xl mb-2 c_icon' />
                        Booking services.</a>
                    <a href="#" className='text-theme  font-medium'>
                        <Icon icon="fluent:payment-16-regular" className='text-5xl mb-2' />Payment and billing.
                    </a>
                    <a href="#" className='text-theme  font-medium'>
                        <Icon icon="fluent:select-all-on-20-regular" className='text-5xl mb-2' />Service provider selection.
                    </a>
                    <a href="#" className='text-theme  font-medium'>
                        <Icon icon="material-symbols:privacy-tip-outline" className='text-5xl mb-2' />Privacy and security.
                    </a>
                </div>



                <Button asChild className="mt-10">
                    <Link href="/help/faq">
                        View All FAQs
                    </Link>
                </Button>


                <h4 className="mt-10 lg:mt-14 text-xl font-bold lg:text-3xl">
                    Contacting Customer Support
                </h4>
                <p className="mt-5 txt">
                    If you cannot find the information you need in our FAQs or if you have a specific issue that requires assistance, our dedicated customer support team is here to help. You can contact us through the following methods:

                </p>
                <div className='grid grid-cols-2 lg:grid-cols-3 gap-4 mt-5'>
                    <a href="#" className='text-theme  font-medium'>

                        <Icon icon="mi:email" className='text-5xl mb-2' />
                        <p className="text-xl font-bold mb-2">
                            Email
                        </p>
                        Send us an email at support@helpRush.in, and one of our representatives will respond to your inquiry promptly.

                    </a>
                    <a href="#" className='text-theme  font-medium'>

                        <Icon icon="quill:chat" className='text-5xl mb-2' />
                        <p className="text-xl font-bold mb-2">
                            Live Chat
                        </p>
                        Look for the live chat icon on our website or within the HelpRush app to chat with a support agent in real-time during our business hours.

                    </a>
                </div>
                <h4 className="mt-10 lg:mt-14 text-xl font-bold lg:text-3xl">
                    Business Hours

                </h4>
                <p className="mt-5 txt">
                    Our customer support team is available to assist you during the following hours:

                </p>
                <p className="text-lg font-bold text-theme mt-3">
                    Monday to Friday:9:00 AM to 6:00 PM IST <br />
                    Saturday and Sunday: Closed.

                </p>
                <p className="mt-3 txt">
                    Please note that response times may vary based on the volume of inquiries, but we strive to address your concerns as quickly as possible.

                </p>
                <h4 className="mt-10 lg:mt-14 text-xl font-bold lg:text-3xl">
                    Feedback and Suggestions

                </h4>
                <p className="mt-5 txt">
                    We value your feedback and suggestions, as they help us improve the HelpRush platform. If you have ideas for enhancements, encounter issues, or wish to provide feedback, please don't hesitate to reach out to us. Your input is essential in making HelpRush better for everyone.

                </p>
                <h4 className="mt-10 lg:mt-14 text-xl font-bold lg:text-3xl">
                    Security and Privacy Concerns
                </h4>
                <p className="mt-5 txt">
                    If you have concerns about the security of your account or any privacy-related issues, please contact us immediately. Your security and privacy are of utmost importance to us, and we take these matters seriously.
                </p>

                <h4 className="mt-10 lg:mt-14 text-xl font-bold lg:text-3xl">
                    Accessibility Assistance
                </h4>
                <p className="mt-5 txt">
                    We are committed to ensuring that our platform is accessible to all users, including those with disabilities. If you require assistance with accessibility features or have suggestions for improving accessibility, please let us know, and we will strive to accommodate your needs.
                    Thank you for choosing HelpRush. We are here to support you and provide a seamless experience as you connect with service providers and enjoy the convenience of our smart marketplace. Your satisfaction and success with HelpRush are our goals, and we look forward to assisting you in any way we can.
                </p>
                {/* <AccordionSegment
                    items={[
                        {
                            title: "How do I create an account?",
                            content: "To create an account, click on the Sign Up button on the top right corner of the page. You will be redirected to a page where you can fill in your details and create an account. You can also sign up using your Google or Facebook account.",
                        },
                    ]}
                /> */}
            </div>


        </section>
    )
}

export default page