import Timeline from '@/components/ui/timeline';
import React from 'react'

export const generateMetadata = async () => {
    return {
        title: "How It Works",
        // description: "Generated by create next app",
    };
}
function page() {
    return (
        <div className="container py-10 lg:py-20">

            <div className="grid items-center lg:grid-cols-2 gap-5 lg:gap-10 pb-10 lg:pb-20">

                <div>
                    <h1 className="text-3xl lg:text-5xl lg:mb-6 font-bold mb-4">
                        How HelpRush Works
                    </h1>


                </div>
                <div>
                    <img src="/img/15185.jpg" alt="" />
                </div>
            </div>
            <section className="pb-10 lg:pb-20">
                <h2 className="text-2xl font-semibold mb-5">For Customers</h2>
                <Timeline
                    items={[
                        {
                            title: "1. Find the Right Expert",
                            content: "Browse through a wide range of services—from home repairs to professional consultations. Use filters to find the best-rated providers near you."
                        },

                        {
                            title: "2. Instant Booking or Scheduled Service",
                            content: "Need help right away? Use RushHour to book an available expert in real time. Prefer a later time? Schedule your service at your convenience."
                        },
                        {
                            title: "3. Transparent Pricing & Comparisons",
                            content: "Compare multiple providers based on price, experience, and reviews. No hidden fees—what you see is what you pay!"
                        },
                        {
                            title: "4. Secure & Hassle-Free Payments",
                            content: "Pay securely through the HelpRush platform using your preferred payment method. We ensure seamless transactions and invoice generation for every service."
                        },
                        {
                            title: "5. Service Completion & Review",
                            content: "Once the service is completed, provide feedback to help maintain quality standards. Ratings help others make informed choices!"
                        }
                    ]}

                />
            </section>

            <section className="pb-10 lg:pb-20">
                <h2 className="text-2xl font-semibold mb-4">For Service Providers</h2>

                <Timeline items={[
                    {
                        title: "1. Sign Up & Get Verified",
                        content: "Join HelpRush by creating a provider profile. Complete KYC, skill verification, and digital onboarding to start receiving bookings."
                    },

                    {
                        title: "2. Offer Services & Set Your Pricing",
                        content: "List the services you offer and set competitive pricing. Your profile will be visible to thousands of potential customers."
                    },
                    {
                        title: "3. Receive & Manage Bookings",
                        content: "Accept requests in real-time or schedule services at your convenience. Customers can reach out via in-app chat for coordination."
                    },
                    {
                        title: "4. Earn & Build Your Reputation",
                        content: "Deliver high-quality service, earn positive reviews, and move up HelpRush’s Provider Levels for better visibility and rewards."
                    },
                    {
                        title: "5. Secure Payments & Growth Opportunities",
                        content: "Receive payments directly through the platform. Access benefits like insurance, training, and exclusive business tools to grow your service."

                    }
                ]} />
               
            </section>

            <section className="">
                <h2 className="text-2xl font-semibold mb-4">Why Choose HelpRush?</h2>
                <p>Trusted Experts for Any Job, Anywhere – Verified professionals with digital KYC and customer reviews.</p>
                <p>Real-Time Service Matching – Book instantly with RushHour or schedule services as per your need.</p>
                <p>Fair & Transparent Marketplace – No hidden fees, clear pricing, and an open platform for providers to build their brand.</p>
                <p>Secure Payments & Support – Easy transactions with customer protection policies and 24/7 support.</p>
                <p className="mt-4 font-bold">Ready to get started? 📲 Download the HelpRush App & Book a Service Today!</p>
            </section>
        </div>
    )
}

export default page