import { Onest } from "next/font/google";
import "./app.scss";
import "./style.css"
import Link from "next/link";
import { Icon } from "@iconify/react";
import NavMenu from "@/components/ui/NavMenu";
import NextTopLoader from "nextjs-toploader";
import { SessionProvider } from "next-auth/react"
import { auth } from "../auth";
import { Toaster } from "sonner";
const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  var currentYear = new Date().getFullYear();
  const session = await auth()

  return (
    <html lang="en">
      <body
        className={`${onest.variable}  antialiased`}
      >
        <SessionProvider >
          <NextTopLoader color="#ff5555" showSpinner={false} />
          <NavMenu loggedIn={session ? true : false} />
          {children}

          <footer id="footer" className="bg-theme pt-10 lg:pt-20 text-sm text-white">
            <div className="container">
              <div className="grid grid-cols-2 lg:grid-cols-5">
                <div className="mb-5 lg:mb-0">
                  <Link href="/" className="footerLogo">
                    <div className="flex items-center">

                      HelpRush
                    </div>
                  </Link>
                  <p className="mt-3 !text-xs">
                    Banao Life Simple
                  </p>
                </div>
                <div >
                  <h3 className="text-lg font-semibold">
                    Company
                  </h3>
                  <ul className="mt-2 flex flex-col gap-2">
                    <li>
                      <a href="#">About us</a>
                    </li>
                    <li>
                      <a href="#">Newsroom</a>
                    </li>
                    <li>
                      <a href="#">Blog</a>
                    </li>
                    <li>
                      <a href="#">Investors</a>
                    </li>
                    <li>
                      <a href="#">Careers</a>
                    </li>
                  </ul>
                  <h3 className="text-lg mt-8 font-semibold">
                    Products
                  </h3>
                  <ul className="mt-2 flex flex-col gap-2">
                    <li>
                      <Link href="/login">Hire</Link>
                    </li>
                    <li>
                      <Link href="/login">Serve</Link>
                    </li>
                    <li>
                      <Link href="/helprush-for-business">HelpRush for Business</Link>
                    </li>
                    <li>
                      <a href="#">Partner with HelpRush</a>
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-semibold">
                    Legal & Policies
                  </h3>
                  <ul className="mt-2 flex flex-col gap-2">
                    <li>
                      <a href="">Terms & conditions</a>
                    </li>
                    <li>
                      <Link href="/general/privacy-policy">Privacy Policy</Link>
                    </li>
                    <li>
                      <Link href="/general/anti-discrimination-policy">Anti-discrimination Policy</Link>
                    </li>
                    <li>
                      <Link href="/general/cancellation-and-refund-policy">Refund & Cancellation Policy</Link>
                    </li>
                    <li>
                      <Link href="/general/dispute-resolution">
                        Dispute Resolution Policy
                      </Link>
                    </li>
                    <li>
                      <Link href="/general/intellectual-property-rights">
                        Intellectual Property Rights
                      </Link>
                    </li>
                    <li>
                      <Link href="/general/service-professional-agreement">
                        Service Professional Agreement
                      </Link>
                    </li>

                  </ul>
                  <h3 className="text-lg mt-8 font-semibold">
                    Resources
                  </h3>
                  <ul className="mt-2 flex flex-col gap-2">
                    <li>
                      <Link href="/resources/how-its-works">How it Works </Link>
                    </li>
                    <li>
                      <Link href="/resources/pricing-and-fee">Pricing & Fees</Link>
                    </li>
                    <li>
                      <Link href="/resources/provider-levels">Provider Levels </Link>
                    </li>

                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-semibold">
                    Customer
                  </h3>
                  <ul className="mt-2 flex flex-col gap-2">
                    <li>
                      <Link href="/customer/code-of-conduct">
                        Code of Conduct
                      </Link>
                    </li>
                    <li>
                      <Link href="/customer/terms-and-conditions">
                        Terms & Conditions
                      </Link>
                    </li>
                  </ul>
                  <h3 className="text-lg mt-8 font-semibold">
                    Provider
                  </h3>
                  <ul className="mt-2 flex flex-col gap-2">
                  <li>
                      <Link href="/provider/how-it-works">
                     How it Works
                      </Link>
                    </li>
                    <li>
                      <Link href="/provider/code-of-conduct">
                        Code of Conduct
                      </Link>
                    </li>
                    <li>
                      <Link href="/provider/provider-agreement">
                        Provider Agreement
                      </Link>
                    </li>
                  </ul>

                </div>
                <div className="grid col-span-2 lg:col-span-1 mt-8 lg:mt-0 grid-cols-2 lg:block">
                  <div>
                    <h3 className="text-lg font-semibold">
                      Follow us
                    </h3>
                    <ul className="mt-2 flex flex-col gap-2">
                      <li>
                        <a href="https://www.linkedin.com/company/helprush/" target="_blank" className="flex gap-1 items-center"><Icon icon="mingcute:linkedin-fill" width="24" height="24" />Linkedin</a>
                      </li>
                      <li>
                        <a href="https://twitter.com/HelprushIN" target="_blank" className="flex gap-1 items-center"><Icon icon="mingcute:social-x-fill" width="24" height="24" /> X</a>
                      </li>
                      <li>
                        <a href="https://www.instagram.com/helprush/" target="_blank" className="flex gap-1 items-center"><Icon icon="mingcute:instagram-line" width="24" height="24" /> Instagram</a>
                      </li>
                      <li>
                        <a href="https://www.facebook.com/Helprush" target="_blank" className="flex gap-1 items-center"><Icon icon="qlementine-icons:facebook-fill-16" width="22" height="22" /> Facebook</a>
                      </li>
                      <li>
                        <a href="https://www.youtube.com/@HelpRush" target="_blank" className="flex gap-1 items-center"><Icon icon="line-md:youtube-filled" width="24" height="24" />YouTube</a>
                      </li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-lg lg:mt-8 font-semibold">
                      Products
                    </h3>
                    <ul className="mt-2 flex flex-col gap-2">
                      <li>
                        <Link href="/help">Help Center</Link>
                      </li>
                      <li>
                        <Link href="/help/faq">FAQs</Link>
                      </li>
                      <li>
                        <a href="/provider/onboarding-guide">Provider Onboarding Guide </a>
                      </li>
                      <li>
                        <a href="#">Contact Support</a>
                      </li>
                    </ul>
                  </div>
                </div>

              </div>
            </div>
            <div className="py-5 lg:py-8 border-t mt-8">
              <div className="container">
                <div className="flex flex-col-reverse lg:flex-row gap-3 justify-between">
                  <p>
                    &copy; {currentYear} HelpRush. All  Rights Reserved.
                  </p>
                  <div className="flex gap-5">
                    <Link href="/accessibility">Accessibility & Website use policy</Link>
                  </div>
                </div>
              </div>
            </div>
          </footer>

          <Toaster position="top-center" />
        </SessionProvider>
      </body>
    </html>
  );
}
