import { Icon } from '@iconify/react';
import React from 'react'


export const generateMetadata = async () => {
    return {
        title: "Provider Onboarding Guide",
        // description: "Generated by create next app",
    };
}
function page() {
    return (
        <main>
            <div className="container py-10 lg:py-20">

                <div className="grid items-center lg:grid-cols-2 gap-5 lg:gap-10 pb-10 lg:pb-14">

                    <div>
                        <h1 className="text-3xl lg:text-5xl !leading-tight lg:mb-6 font-bold mb-4">
                            Get Verified & Start Earning With HelpRush!
                        </h1>
                        <p className='text lg:text-lg'>
                            Follow this simple guide to onboard smoothly and start accepting jobs in minutes
                        </p>

                        <a href="" className="btn inline-block mt-4">
                            Download App
                        </a>
                    </div>
                    <div>
                        <img className='max-w-md w-full lg:ml-auto' src="/img/c0f2850c982c536320f5a803cbf851f8.png" alt="" />
                    </div>
                </div>
            </div>
            <div className="bg-indigo-50 bg-opacity-65 py-5 lg:py-10">
                <div className="grid items-center  gap-10 max-w-4xl mx-auto lg:grid-cols-2">
                    <div>
                        <img src="/img/appscreen11.png" className='max-w-[250px] w-full lg:mr-auto' alt="" />
                    </div>
                    <div className="col">
                        <h3 className='text-8xl font-bold text-theme '>
                            01
                        </h3>
                        <h2 className='text-2xl font-bold !leading-tight lg:text-[33px]'>
                            Sign Up & Registration
                        </h2>
                        <p className='txt mt-3'>
                            Mobile OTP verification. <br />
                            Identity verification in partnership with Digilocker (DigiLocker + Selfie). <br />
                            Skill verification  <br />
                            Submit application
                        </p>
                    </div>

                </div>
            </div>
            <div className="py-5 lg:py-10">
                <div className="grid items-center gap-10 max-w-4xl mx-auto lg:grid-cols-2 mb-5">
                    <div className='lg:order-2'>
                        <img src="/img/appscreen11.png" className='max-w-[250px] w-full lg:ml-auto' alt="" />
                    </div>
                    <div className="col">
                        <h3 className='text-8xl font-bold text-theme '>
                            02
                        </h3>
                        <h2 className='text-2xl font-bold !leading-tight lg:text-[33px]'>
                            Verification & Approval
                        </h2>
                        <p className='txt mt-3'>
                            Application scrutiny  <br />
                            Background checks & in-person interview <br />
                            Track status by loggin in to the app  <br />
                            Account Activation (Normally with 24-48 Hrs)
                        </p>
                    </div>

                </div>
            </div>
            <div className="bg-indigo-50 bg-opacity-65 py-5 lg:py-10">
                <div className="grid items-center gap-10 max-w-4xl mx-auto lg:grid-cols-2 mb-5">
                    <div>
                        <img src="/img/appscreen11.png" className='max-w-[250px] w-full lg:mr-auto' alt="" />
                    </div>
                    <div className="col">
                        <h3 className='text-8xl font-bold text-theme '>
                            03
                        </h3>
                        <h2 className='text-2xl font-bold !leading-tight lg:text-[33px]'>
                            Profile setup
                        </h2>
                        <p className='txt mt-3'>
                            Fill in profile details <br />
                            Add services & set Pricing <br />
                            enable Availability & Working hours
                        </p>
                    </div>

                </div>
            </div>
            <div className="py-5 lg:py-10">
                <div className="grid items-center gap-10 max-w-4xl mx-auto lg:grid-cols-2 mb-5">
                    <div className='lg:order-2'>
                        <img src="/img/appscreen11.png" className='max-w-[250px] w-full lg:ml-auto' alt="" />
                    </div>
                    <div className="col">
                        <h3 className='text-8xl font-bold text-theme '>
                            04
                        </h3>
                        <h2 className='text-2xl font-bold !leading-tight lg:text-[33px]'>
                            Training & Guidelines
                        </h2>
                        <p className='txt mt-3'>
                            Platform orientation <br />Ï
                            Safety training <br />Ï
                            Social security , growth & Levels systems
                        </p>
                    </div>

                </div>
            </div>
            <div className="bg-indigo-50 bg-opacity-65 py-5 lg:py-10">
                <div className="grid items-center gap-10 max-w-4xl mx-auto lg:grid-cols-2 mb-5">
                    <div>
                        <img src="/img/appscreen11.png" className='max-w-[250px] w-full lg:mr-auto' alt="" />
                    </div>
                    <div className="col">
                        <h3 className='text-8xl font-bold text-theme '>
                            05
                        </h3>
                        <h2 className='text-2xl font-bold !leading-tight lg:text-[33px]'>
                            Start Accepting Bookings
                        </h2>
                        <p className='txt mt-3'>
                            Receive & Accept service bookings <br />
                            Navigate to customer location on scheduled time <br />
                            Chat & Call customers within the app <br />
                            Fulfill orders
                        </p>
                    </div>

                </div>
            </div>
            <div className="py-5 lg:py-10">
                <div className="grid items-center gap-10 max-w-4xl mx-auto lg:grid-cols-2 mb-5">
                    <div className='lg:order-2'>
                        <img src="/img/appscreen11.png" className='max-w-[250px] w-full lg:ml-auto' alt="" />
                    </div>
                    <div className="col">
                        <h3 className='text-8xl font-bold text-theme '>
                            06
                        </h3>
                        <h2 className='text-2xl font-bold !leading-tight lg:text-[33px]'>
                            Payments & earnings
                        </h2>
                        <p className='txt mt-3'>

                            Secure payments <br />
                            track earnings in the app <br />
                            withdraw payment
                        </p>
                    </div>

                </div>
            </div>
            <div className="bg-indigo-50 bg-opacity-65 py-5 lg:py-10">
                <div className="grid items-center gap-10 max-w-4xl mx-auto lg:grid-cols-2 mb-5">
                    <div>
                        <img src="/img/appscreen11.png" className='max-w-[250px] w-full lg:mr-auto' alt="" />
                    </div>
                    <div className="col">
                        <h3 className='text-8xl font-bold text-theme '>
                            07
                        </h3>
                        <h2 className='text-2xl font-bold !leading-tight lg:text-[33px]'>
                            Reviews & Growth
                        </h2>
                        <p className='txt mt-3'>

                            Request customers ratings & reviews <br />
                            Track performance & Progress <br />
                            Check analytics & avail trainings
                        </p>
                    </div>

                </div>
            </div>
        </main>
    )
}

export default page