import AccordionSegment from '@/components/ui/accordionSegment';
import React from 'react'

export const generateMetadata = async () => {
    return {
        title: "FAQs",
        // description: "Generated by create next app",
    };
}

function page() {

    const items = [
        {
            title: "What is HelpRush?",
            content: "HelpRush is an innovative consumer tech platform that connects users with trusted service providers for a wide range of home and professional services. From repairs and cleaning to beauty and wellness, HelpRush enables real-time bookings and seamless service experiences.",
        },
        {
            title: "How does HelpRush work?",
            content: "HelpRush allows customers to browse, compare, and book verified service providers instantly. Providers undergo a thorough verification process and are rated based on experience, performance, and customer feedback. Simply choose a service, select a provider, and get the job done hassle-free.",
        },
        {
            title: "Where is HelpRush available?",
            content: "HelpRush is currently operational in multiple locations and is expanding rapidly. You can check service availability in your area by entering your location in the app or website.",
        },
        {
            title: "Is HelpRush free to use?",
            content: "The HelpRush app is free to download and use. Customers only pay for the services they book. Providers may be subject to platform fees based on their level and transactions.",
        },
        {
            title: "How do I book a service?",
            content: "Open the HelpRush app or website. Select the service you need. Compare providers based on price, rating, and availability. Confirm your booking and make a payment if required. Track your provider and get the job done.",
        },
        {
            title: "Can I schedule a service in advance?",
            content: "Yes, you can book services for a later date and time as per your convenience.",
        },
        {
            title: "How do I pay for a service?",
            content: "Payments can be made via Razorpay using credit/debit cards, UPI, net banking, or wallets. Cash payments may also be available for certain services.",
        },
        {
            title: "Can I cancel my booking?",
            content: "Yes, cancellations are subject to HelpRush's Cancellation & Refund Policy, which varies based on the time of cancellation. A nominal fee may apply if the provider has already committed time and resources to your request.",
        },
        {
            title: "How do I track my provider?",
            content: "Once your booking is confirmed, you can track the provider’s real-time location and estimated arrival time through the app.",
        },
        {
            title: "What if I am not satisfied with the service?",
            content: "If you're not satisfied, you can report the issue via the app. We will review your case and, if applicable, offer refunds or reassign a provider.",
        },
        {
            title: "How do I become a provider on HelpRush?",
            content: "To become a provider, download the HelpRush Provider app, complete the onboarding process, submit required documents, and pass our verification checks.",
        },
        {
            title: "What are Provider Levels?",
            content: "Providers on HelpRush are classified into levels based on experience, customer ratings, and platform engagement. Higher levels unlock more benefits, increased visibility, and better earnings.",
        },
        {
            title: "What are the benefits of joining HelpRush as a provider?",
            content: "Access to a large customer base. Flexible working hours. Secure and timely payments. Skill enhancement programs and training. Insurance and social security benefits for higher-level providers.",
        },
        {
            title: "How do providers get paid?",
            content: "Payments are processed securely through the app and transferred directly to the provider’s registered bank account after deductions (if applicable).",
        },
        {
            title: "Are there any fees for providers?",
            content: "HelpRush charges a platform fee on successful transactions. The fee structure varies based on the provider's level and chosen subscription plan.",
        },
        {
            title: "Are providers on HelpRush verified?",
            content: "Yes, all providers undergo KYC verification, background checks, and skill assessments to ensure trust and safety.",
        },
        {
            title: "What should I do if I face an issue with a provider?",
            content: "You can report the issue through the app or contact HelpRush support for resolution.",
        },
        {
            title: "How does HelpRush ensure customer safety?",
            content: "HelpRush implements strict provider screening, real-time tracking, customer feedback systems, and insurance options to ensure a safe service experience.",
        },
        {
            title: "Does HelpRush offer services for businesses?",
            content: "Yes, HelpRush for Business provides tailored solutions for enterprises, including bulk service bookings, vendor management, and dedicated customer support.",
        },
        {
            title: "How can businesses partner with HelpRush?",
            content: "Businesses can sign up on the HelpRush website under the HelpRush for Business section or contact our sales team for partnerships.",
        },
        {
            title: "I forgot my password. How do I reset it?",
            content: "Click on Forgot Password? on the login screen and follow the instructions to reset your password.",
        },
        {
            title: "How can I update my profile information?",
            content: "You can edit your profile details in the Account Settings section of the app.",
        },
        {
            title: "How do I contact HelpRush support?",
            content: "You can reach our support team via the Help & Support section in the app or email us at support@helprush.in.",
        },
        {
            title: "Can I deactivate or delete my HelpRush account?",
            content: "Yes, you can request account deactivation or deletion by contacting customer support.",
        },
    ];

    return (

        <section className="py-10 lg:py-20">
            <div className="container">
                <h3
                    className='text-3xl font-bold lg:text-5xl'>
                    Frequently Asked Questions (FAQs)
                </h3>

                <div className="mt-10">
                    <AccordionSegment
                        items={items}
                    />
                </div>
                <p className="txt mt-10">
                    Still have questions? Reach out to us via the HelpRush app or website for assistance!
                </p>
            </div>


        </section>
    )
}

export default page