import Timeline from '@/components/ui/timeline';
import { Icon } from '@iconify/react';
import Link from 'next/link';
import React from 'react'

export const generateMetadata = async () => {
  return {
    title: "How It Works",
    // description: "Generated by create next app",
  };
}
function page() {
  return (
    <main>
      <div className="container py-10 lg:py-20">
        <h2 className='text-2xl font-bold !leading-tight lg:text-4xl'>
          Grow Your Business with HelpRush                </h2>
        <p className='txt mt-3 max-w-3xl'>
          More bookings, more earnings, more growth—join HelpRush and get connected with customers instantly.       </p>
        <div className='mt-5 max-w-3xl lg:mt-8'>
          <ul className='flex flex-col gap-2'>
            <li>
              <p>
                HelpRush is designed to help skilled professionals like you find more work, build trust, and grow your business effortlessly.
              </p>
            </li>
            <li className='lg:flex gap-2'>

              <Icon icon='fluent:checkbox-checked-16-filled' className='text-theme text-2xl ' />
              <p>
                <strong>  Get Discovered </strong> - Customers in your area can find and book you directly. </p>
            </li>
            <li className='lg:flex gap-2'>
              <Icon icon='fluent:checkbox-checked-16-filled' className='text-theme text-2xl ' />
              <p>
                <strong> Work on Your Terms</strong> - Set your availability, pricing, and preferred service areas. </p>
            </li>
            <li className='lg:flex gap-2'>
              <Icon icon='fluent:checkbox-checked-16-filled' className='text-theme text-2xl ' />
              <p>
                <strong>  Secure & Guaranteed Payments</strong> -  No chasing payments—earn hassle-free with every completed job.   </p>
            </li>
            <li className='lg:flex gap-2'>
              <Icon icon='fluent:checkbox-checked-16-filled' className='text-theme text-2xl ' />
              <p className='w-full'>
                <strong>  Level Up & Earn More</strong> - Our unique provider Levels system rewards top performers with better visibility and benefits.
              </p>
            </li>
            <li>
              <p>
                Join HelpRush today and take control of your success!
              </p>
            </li>

          </ul>
          <Link href="/signup" className="btn inline-block mt-5 lg:mt-8">Signup Now</Link>
        </div>
      </div>

      <div className=" bg-indigo-50 bg-opacity-60 py-10 lg:py-20">
        <div className="container">
          <h4 class="text-2xl font-bold">A Quick Guide to HelpRush for Providers</h4>
          <p className='mb-10'>
            Here’s how HelpRush empowers skilled professionals to connect with customers, grow their business, and earn on their terms, step by step: </p>
          <div className="grid lg:grid-cols-4 gap-5 lg:gap-10">
            <div className="col">
              <h3 className='text-8xl font-bold text-theme '>
                01
              </h3>
              <h2 className='text-2xl font-bold !leading-tight lg:text-[33px]'>
                Sign Up & Get Verified
              </h2>
              <p className='txt mt-3 !text-sm'>
                Create your profile, complete KYC, and get verified to start receiving bookings.   </p>
            </div>
            <div className="col">
              <h3 className='text-8xl font-bold text-theme '>
                02
              </h3>
              <h2 className='text-2xl font-bold !leading-tight lg:text-3xl'>
                Set Your Preferences
              </h2>
              <p className='txt mt-3 !text-sm'>
                Choose your services, set your availability, and define your work area—all on your terms</p>
            </div>
            <div className="col">
              <h3 className='text-8xl font-bold text-theme '>
                03
              </h3>
              <h2 className='text-2xl font-bold !leading-tight lg:text-3xl'>
                Get Bookings & Deliver Services
              </h2>
              <p className='txt mt-3 !text-sm'>
                Customers find and book you instantly. Accept jobs, provide top-quality service, and build your reputation.</p>
            </div>
            <div className="col">
              <h3 className='text-8xl font-bold text-theme '>
                04
              </h3>
              <h2 className='text-2xl font-bold !leading-tight lg:text-3xl'>
                Earn & Level Up
              </h2>
              <p className='txt mt-3 !text-sm'>
                Get paid securely for every completed job. Deliver great service to unlock higher levels and exclusive benefits! </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}

export default page