import React from 'react'

export const generateMetadata = async () => {
    return {
        title: "Provider Levels",
        // description: "Generated by create next app",
    };
}
function page() {
    return (
        <div className="container py-10 lg:py-20">
            <h1 className="text-3xl font-bold mb-4">HelpRush Provider Levels System</h1>
            <p className="mb-4">
                At HelpRush, we believe in recognizing and rewarding excellence. Our Provider Levels system is designed to help professionals grow, build trust, and access greater opportunities on the platform. The levels signify a provider's experience, reliability, and commitment to quality service.
            </p>

            <h2 className="text-2xl font-semibold mt-6 mb-3">Levels Overview</h2>
            <p className="mb-4">
                Providers progress through levels based on performance, customer feedback, and adherence to platform guidelines. Each level unlocks new benefits and greater visibility.
            </p>

            <h3 className="text-xl font-medium mt-3 mb-2">Level 1 - Starter</h3>
            <p className="ml-6"><b>Entry Criteria:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Basic profile verification completed (KYC, ID verification, phone number, email, and bank details).</li>
                <li>Signed up and onboarded via the HelpRush Provider App.</li>
                <li>Minimum 1 completed service booking.</li>
            </ul>
            <p className="ml-6"><b>Benefits:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Access to job requests.</li>
                <li>Standard visibility in search results.</li>
                <li>Access to customer ratings and reviews.</li>
            </ul>
            <p className="ml-6"><b>Restrictions:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Limited to basic service categories.</li>
                <li>No premium or high-value bookings.</li>
            </ul>

            <h3 className="text-xl font-medium mt-3 mb-2">Level 2 - Verified Professional</h3>
            <p className="ml-6"><b>Entry Criteria:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Minimum 10 completed service bookings with an average rating of 4.0+.</li>
                <li>Completion of additional profile information (work samples, certifications, etc.).</li>
                <li>No active policy violations or disputes.</li>
            </ul>
            <p className="ml-6"><b>Benefits:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Higher ranking in search results.</li>
                <li>Ability to bid on premium service requests.</li>
                <li>Access to exclusive training resources.</li>
            </ul>
            <p className="ml-6"><b>Restrictions:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Can only accept a limited number of high-value bookings.</li>
            </ul>

            <h3 className="text-xl font-medium mt-3 mb-2">Level 3 - Trusted Expert</h3>
            <p className="ml-6"><b>Entry Criteria:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Minimum 50 completed bookings with an average rating of 4.5+.</li>
                <li>Completion of HelpRush’s skill verification process (AI & DigiLocker-based verification).</li>
                <li>Mandatory enrollment in accident and life insurance.</li>
                <li>No major complaints or policy violations in the last 6 months.</li>
            </ul>
            <p className="ml-6"><b>Benefits:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Priority placement in search results.</li>
                <li>Reduced platform fees.</li>
                <li>Exclusive access to business growth tools and analytics.</li>
                <li>Invitation to participate in promotional campaigns.</li>
            </ul>
            <p className="ml-6"><b>Restrictions:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Required to maintain consistent response times and high completion rates.</li>
            </ul>

            <h3 className="text-xl font-medium mt-3 mb-2">Level 4 - Elite Provider</h3>
            <p className="ml-6"><b>Entry Criteria:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Minimum 200 completed bookings with an average rating of 4.8+.</li>
                <li>AI-driven trust score in the top 10%.</li>
                <li>Fully compliant with all training, insurance, and policy requirements.</li>
                <li>No customer disputes or cancellations in the last 6 months.</li>
            </ul>
            <p className="ml-6"><b>Benefits:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Highest ranking in search results.</li>
                <li>Significantly reduced platform fees.</li>
                <li>Early access to new features and premium service requests.</li>
                <li>Personalized branding opportunities within the HelpRush app.</li>
                <li>Dedicated account support.</li>
            </ul>
            <p className="ml-6"><b>Restrictions:</b></p>
            <ul className="list-inside list-disc ml-6">
                <li>Must maintain top-tier service quality.</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-6 mb-3">Demotions and Level Maintenance</h2>
            <p className="ml-6">
                Providers must consistently meet level criteria to maintain their status. Failure to do so may result in:
            </p>
            <ul className="list-inside list-disc ml-6">
                <li>Temporary demotion to a lower level.</li>
                <li>Loss of associated benefits until performance improves.</li>
                <li>Re-evaluation based on customer feedback and service history.</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-6 mb-3">RushHour & Emergency Bookings</h2>
            <p className="ml-6">
                Higher-level providers receive first preference for urgent service requests through HelpRush’s real-time "RushHour" system.
            </p>

            <h2 className="text-2xl font-semibold mt-6 mb-3">AI-Powered Smart Matching</h2>
            <p className="ml-6">
                HelpRush utilizes an AI-driven algorithm that considers provider levels, ratings, skill verification, and response times to match providers with the best-suited customers.
            </p>

            <h2 className="text-2xl font-semibold mt-6 mb-3">Conclusion</h2>
            <p className="ml-6">
                The HelpRush Provider Levels system is designed to create a fair, transparent, and rewarding environment for skilled professionals. By consistently delivering excellent service, providers can unlock better opportunities and maximize their earnings.
            </p>
            <p className="ml-6 mt-4">
                Ready to level up? Keep delivering top-notch service and enjoy the benefits of growing with HelpRush!
            </p>
            <p className="mt-6">
                For any questions or assistance, reach out to our support team.
            </p>
        </div>
    )
}

export default page