import Timeline from '@/components/ui/timeline';
import { Icon } from '@iconify/react';
import React from 'react'

export const generateMetadata = async () => {
    return {
        title: "Provider Levels",
        // description: "Generated by create next app",
    };
}
function page() {
    return (
        <main>
            <div className="container py-8 lg:py-10">

                <div className="grid items-center lg:grid-cols-2 gap-5 lg:gap-10">
                    <div className='lg:order-2'>
                        <img className='max-w-md w-full ml-auto' src="/img/tempImageSxW9Hk.png" alt="" />
                    </div>
                    <div>
                        <h1 className="text-3xl lg:text-5xl !leading-tight lg:mb-6 font-bold mb-4">
                            GROW . EARN . LEVEL UP.
                        </h1>
                        <p className='txt lg:!text-lg'>
                            The more you deliver, the more you unlock. Climb the HelpRush Provider Levels and enjoy better earnings, visibility & benefits  </p>
                    </div>

                </div>


            </div>
            <div className=" bg-indigo-50 bg-opacity-60 py-10 lg:py-20">

                <div className="container">
                    <p className='lg:text-xl text-center max-w-2xl mx-auto text-lg lg:mb-20 mb-10'>
                        Providers progress through levels based on performance, ratings, and experience. Higher levels mean better visibility, lower fees, and premium benefits.
                    </p>
                    <div className="max-w-md mx-auto">
                        <Timeline

                            items={[
                                {
                                    icon: <Icon icon="pajamas:warning" />,
                                    bg: '#FF5E58',
                                    title: "Level 1",
                                    text: "white",
                                    content: <p>
                                        Starter (Basic verification + 1 booking) → Standard visibility  </p>
                                },
                                {
                                    icon: <Icon icon="mingcute:check-fill" />,
                                    bg: '#FFCC00',
                                    title: "Level 2",
                                    content: <p>
                                        Verified Professional (10 bookings + 4.0+ rating) → Better ranking & access to premium jobs </p>
                                },
                                {
                                    icon: <Icon icon="simple-line-icons:badge" />,
                                    bg: '#009951',
                                    text: "white",
                                    title: "Level 3",
                                    content: <p>
                                        Trusted Expert (50 bookings + skill verification) → Lower fees & business growth tools </p>
                                },
                                {
                                    icon: <Icon icon="material-symbols:star-outline" />,
                                    bg: '#008080',
                                    text: "white",
                                    title: "Level 4",
                                    content: <p>
                                        Elite Provider (200+ bookings + AI trust score) → Highest ranking, premium jobs & branding perks
                                    </p>
                                },

                            ]} />
                    </div>
                    <div className="text-center flex flex-col gap-4 lg:flex-row mt-5 lg:mt-14 lg:gap-8 items-center justify-center">
                        <p>
                            Still curious about Levels?
                        </p>
                        <a href="" className='btn inline-block '> Contact HelpRush Support </a>
                    </div>
                </div>
            </div>
        </main>
    )
}


export default page