import React from 'react'

export const generateMetadata = async () => {
    return {
        title: "Service Professional Agreement",
        // description: "Generated by create next app",
    };
}
function page() {
    return (
        <div className="container py-10 lg:py-20">
            <h1 className="text-3xl font-bold mb-4">Service Professional Agreement</h1>
            <p>Effective Date: [Date]</p>
            <p>Last Updated: [Date]</p>
            <p>This Service Professional Agreement ("Agreement") is entered into between Horfay Taqnia Private Limited (which owns and operates the HelpRush platform) and Service Professionals (Pros) who provide services through the HelpRush platform. By registering as a Pro, you agree to abide by the terms outlined in this Agreement.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">1. Appointment & Registration</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">1.1 Definition of Pros</h3>
            <p>Service Professionals (Pros) are individuals enlisted by registered Providers on the HelpRush platform to fulfill customer orders.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">1.2 Registration Process</h3>
            <p>Pros can only be added by registered Providers through their profiles on the HelpRush platform.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">2. Screening & Background Verification</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">2.1 Provider Responsibility</h3>
            <p>Providers shall conduct thorough background checks, identity verification, and review relevant antecedents before adding Pros.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">2.2 Record Maintenance</h3>
            <p>Providers are responsible for maintaining complete records of Pros, which HelpRush may verify at any time.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">3. Responsibilities & Conduct</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">3.1 Professional Behavior</h3>
            <p>Pros must conduct themselves professionally, maintaining courtesy, respect, and ethical behavior in all interactions.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">3.2 Profile Authenticity</h3>
            <p>Pros must upload a genuine recent photograph and complete all required profile sections.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">3.3 Compliance</h3>
            <p>Pros must adhere to all codes of conduct, platform rules, and policies applicable to Providers and Pros.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">4. Exit & Dispute Resolution</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">4.1 Exit Requests</h3>
            <p>Pros may submit exit requests through the HelpRush app if they wish to leave their current Provider.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">4.2 Approval of Exit</h3>
            <p>Providers must approve exit requests if no outstanding balances or disputes exist.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">4.3 Dispute Handling</h3>
            <p>If a Provider rejects an exit request three times, Pros can raise a dispute within the app, requesting HelpRush intervention.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">5. Business Integrity & Platform Use</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">5.1 No Off-Platform Solicitation</h3>
            <p>Pros are strictly prohibited from soliciting business from HelpRush customers outside the platform.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">5.2 Breach Consequences</h3>
            <p>Violation of this provision may result in termination of the Pro and potential action against the associated Provider.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">6. Training & Skill Development</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">6.1 Commitment to Learning</h3>
            <p>Pros must participate in training programs organized by Providers and HelpRush to enhance their skills.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">6.2 Compliance Training</h3>
            <p>Pros must attend safety, quality assurance, and compliance training as mandated by HelpRush.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">7. Compensation & Financial Matters</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">7.1 Provider-Paid Compensation</h3>
            <p>Pros will receive compensation, salaries, or dues as per their mutual agreement with their Providers.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">7.2 No Financial Claims on HelpRush</h3>
            <p>HelpRush is not responsible for wage settlements, compensation, or financial negotiations between Providers and Pros.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">7.3 No Independent Earnings from HelpRush</h3>
            <p>Pros are not entitled to commissions, earnings, or rewards directly from HelpRush.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">8. Insurance & Benefits</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">8.1 Mandatory Insurance</h3>
            <p>Pros must maintain valid medical and life insurance coverage.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">8.2 Pension & Benefits</h3>
            <p>Pros may apply for the pension program if recommended by their Providers and if they meet HelpRush’s conditions.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">9. Safety, Compliance & Legal Responsibilities</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">9.1 Legal Adherence</h3>
            <p>Pros must comply with all applicable government laws, HelpRush policies, and industry regulations.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">9.2 Workplace Safety</h3>
            <p>Pros must use safety gear, follow traffic laws, and attend safety training sessions.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">9.3 Health & Well-Being</h3>
            <p>Pros should take appropriate health precautions, including vaccinations, and must not work when unwell.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">10. Duration & Termination</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">10.1 Agreement Validity</h3>
            <p>This Agreement is effective upon a Pro’s registration on the HelpRush platform and remains valid until terminated by either party.</p>
            <h3 className="text-lg font-bold mt-2 mb-1">10.2 Termination Notice</h3>
            <p>Either party may terminate this Agreement by providing written notice with a reasonable notice period.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">11. Governing Law & Dispute Resolution</h2>
            <h3 className="text-lg font-bold mt-2 mb-1">11.1 Legal Jurisdiction</h3>
            <p>This Agreement is governed by and construed in accordance with the laws of [Jurisdiction].</p>
            <h3 className="text-lg font-bold mt-2 mb-1">11.2 Dispute Handling</h3>
            <p>Disputes shall first be resolved through mutual discussion. If unresolved, the dispute will be escalated to HelpRush’s internal mediation process.</p>

            <p>By registering as a Service Professional on HelpRush, you acknowledge and agree to abide by the terms of this Agreement.</p>

            <p>For Any Queries, Contact HelpRush Support.</p>
        </div>
    )
}

export default page