import React from 'react'

export const generateMetadata = async () => {
    return {
        title: "Intellectual Property Rights",
        // description: "Generated by create next app",
    };
}

function page() {
    return (
        <div className="container py-10 lg:py-20">
            <h1 className="text-3xl font-bold mb-4">Intellectual Property Rights of HelpRush</h1>
            <p>All text, graphics, editorial content, data, formatting, graphs, designs, HTML, look and feel, photographs, music, sounds, images, software, videos, typefaces, and other content, including HelpRush designs, trademarks, and logos (collectively referred to as "Proprietary Material"), presented to Users on the HelpRush Platform is the exclusive property of HelpRush, excluding User Generated Content. Users hereby grant HelpRush a license to use User Generated Content. The Proprietary Material is protected by all forms of intellectual property laws, including copyright, patents, and other proprietary rights, in all existing and future forms of media and technologies.</p>

            <p>HelpRush owns all rights to the Proprietary Material, including the coordination, selection, arrangement, and enhancement of such Proprietary Materials. Users are expressly prohibited from copying, downloading, using, redesigning, reconfiguring, or retransmitting any content from the HelpRush Platform without the express prior written consent of HelpRush. Additionally, Users must obtain the consent of the holder of the rights to any User Generated Content before using it for any purpose other than as permitted herein.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">Service Marks and Trademarks:</h2>
            <p>The service marks and trademarks associated with HelpRush, including but not limited to "HelpRush," "HelpRush for Good," and associated logos are the exclusive property of HelpRush. Any other trademarks, service marks, logos, and/or trade names appearing on the HelpRush Platform belong to their respective owners.</p>

            <h2 className="text-xl font-bold mt-4 mb-2">Proprietary Marks and Logos:</h2>
            <p>HelpRush's proprietary marks and logos are not available for use by users, including Service Providers. Users, including Service Providers, may not copy or use any of these marks, logos, or trade names without the express prior written consent of HelpRush.</p>

            <p>Users acknowledge and agree that any unauthorized use of the Proprietary Material, or any other intellectual property owned by HelpRush may result in legal action to protect HelpRush's rights. If Users have questions or require clarification regarding the use of intellectual property, they should contact HelpRush for guidance.</p>
        </div>
    )
}

export default page